<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20221008000951" tests="1" file="unittest/loader.py" time="0.016" timestamp="2022-10-08T00:09:51" failures="0" errors="1" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="basic_tests" time="0.016" timestamp="2022-10-08T00:09:51">
		<error type="ImportError" message="Failed to import test module: basic_tests
Traceback (most recent call last):
  File &quot;F:\Paths\Pythons\Python310\lib\unittest\loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;e:\d-devxxx\python\16_pythonfor\buildtoolpybuilder\src\unittest\python\basic_tests.py&quot;, line 4, in &lt;module&gt;
    from helloworld import helloworld
ModuleNotFoundError: No module named 'helloworld'
"><![CDATA[Traceback (most recent call last):
  File "F:\Paths\Pythons\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "F:\Paths\Pythons\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "F:\Paths\Pythons\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "F:\Paths\Pythons\Python310\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: basic_tests
Traceback (most recent call last):
  File "F:\Paths\Pythons\Python310\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "e:\d-devxxx\python\16_pythonfor\buildtoolpybuilder\src\unittest\python\basic_tests.py", line 4, in <module>
    from helloworld import helloworld
ModuleNotFoundError: No module named 'helloworld'

]]></error>
	</testcase>
</testsuite>
